services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
      - .:/app
      - ../distill:/distill:ro
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      DOCKER_HOST_IP: host.docker.internal
      NUM_ROUNDS: ${NUM_ROUNDS:-3}
    networks:
      - flwr_network
    deploy:
      resources:
        limits:
          cpus: '0.5'   

  client:
    image: flwr_client
    build:
      context: .
      dockerfile: Dockerfile.client
    labels:
      - "type=client"
    depends_on:
      - server
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
    environment:
      NUM_ROUNDS: ${NUM_ROUNDS:-3}
      NUM_CPUS: ${NUM_CPUS:-1}
      NUM_RAM: ${NUM_RAM:-2}
      SERVER_ADDRESS: server:8080
    deploy:
      resources:
        limits:
          cpus: ${NUM_CPUS:-1}
          memory: ${NUM_RAM_LIMIT:-2g}
    command: sh -c "sleep 5 && python client.py"

networks:
  flwr_network:
    driver: bridge
